---
# this is the setup for the hosts that ping each other
- hosts: default
  remote_user: benny
  sudo: True
  vars_files: vault.yml
  tasks:
    - synchronize:
        src: ping/
        dest: /home/benny/ping/
    - apt:
        name: python-pip
        state: present
    - pip:
        requirements: /home/benny/ping/requirements.txt
    - environment:
        REDIS_HOST: "{{ redis_host }}"
    - environment:
        REDIS_PORT: "{{ redis_port }}"
    - cron:
        name: "ping latency"
        job: "sudo python /home/benny/ping/ping.py"
